python-flask-example-heroku materials
realpython/materials pull request #181
Opened 2021-01-24 05:17 UTC by miguelgarcia

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2021-02-10 13:23 UTC, bzaczynski commented on python-flask-example-heroku/.gitignore
> +venv
We can add the `__pycache__/` folder too.

2021-02-10 13:24 UTC, bzaczynski commented on python-flask-example-heroku/config.py
> +class Config(object):
Use class declaration syntax form Python 3:

```suggestion
class Config:
```

2021-02-10 13:26 UTC, bzaczynski commented on python-flask-example-heroku/app.py
> +    return f"The configured secret key is {app.config.get('SECRET_KEY')}"
The latest version from the tutorial looks like this:

```suggestion
import os
from flask import Flask

app = Flask(__name__)
env_config = os.getenv("APP_SETTINGS", "config.DevelopmentConfig")
app.config.from_object(env_config)


@app.route("/")
def index():
    secret_key = app.config.get("SECRET_KEY")
    return f"The configured secret key is {secret_key}."
```

2021-02-10 13:27 UTC, bzaczynski commented on python-flask-example-heroku/config.py
> +    SECRET_KEY = os.getenv("SECRET_KEY", "this-is-read-from-env")
According to the tutorial, this should be the following:

```suggestion
    SECRET_KEY = os.getenv("SECRET_KEY", "this-is-the-default-key")
```

2021-02-10 13:28 UTC, bzaczynski commented on python-flask-example-heroku/config.py
> +    DEBUG = True
The rest is this:

```suggestion
class ProductionConfig(Config):
    pass


class StagingConfig(Config):
    DEBUG = True


class DevelopmentConfig(Config):
    DEBUG = True
    DEVELOPMENT = True
```

2021-02-10 13:28 UTC, bzaczynski requested changes
@miguelgarcia Please update the accompanying PR in the materials repository to reflect your changes in the tutorial. Thanks!

2021-02-16 10:24 UTC, bzaczynski commented
lgtm

2021-03-08 20:31 UTC, jaschmitt approved these changes

2021-03-08 20:33 UTC, merged