Add materials for the Code Image Generator tutorial
realpython/materials pull request #411
Opened 2023-07-06 12:38 UTC by acsany

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2023-08-10 14:48 UTC, lpozo requested changes
@acsany Hey!

I flagged a few details in the steps. It'd be nice to fully check the code with the article.

I typically create the step folders once I finish the TR updates. At this point, it should be a matter of following the article.

2023-08-10 14:48 UTC, lpozo commented on code-image-generator/source_code_step_01/templates/code_input.html
> +{% endblock content %}
We can add the spaces to match the code in the article.

2023-08-10 14:48 UTC, lpozo commented on code-image-generator/source_code_step_02/app.py
> +app.secret_key = "mysecretkey"
We're not using this secret key any longer.

2023-08-10 14:48 UTC, lpozo commented on code-image-generator/source_code_step_02/static/styles.css
> +}
```suggestion
    flex-wrap: wrap;
}
```

2023-08-10 14:48 UTC, lpozo commented on code-image-generator/source_code_step_03/app.py
> +app.secret_key = "mysecretkey"
secret_key

2023-08-10 14:48 UTC, lpozo commented on code-image-generator/source_code_step_03/static/styles.css
> +}
```suggestion
    flex-wrap: wrap;
}
```

2023-08-10 14:48 UTC, lpozo commented on code-image-generator/source_code_step_03/templates/base.html
> +      Code to Image
```suggestion
      Code to Image {% block title %}{% endblock %}
```

2023-08-15 22:22 UTC, KateFinegan approved these changes

2023-08-15 22:22 UTC, merged