Code files for Type Hints tutorial
realpython/materials pull request #441
Opened 2023-10-02 03:39 UTC by claudian37

Adding sample code files for tutorial on [How to Use Type Hints for Multiple Return Types in Python](https://realpython.com/python-type-hints-multiple-types/)

2023-10-02 08:10 UTC, bzaczynski requested changes
@claudian37 Hey Claudia! Thanks for creating a separate PR in the materials repository. Please find a few comments and let me know if you have further questions.

2023-10-02 08:10 UTC, bzaczynski commented on python-type-hints-multiple-types/README.md
> +
There's an extra blank line that we can remove from here.

2023-10-02 08:10 UTC, bzaczynski commented on python-type-hints-multiple-types/01_type_hints_for_one_piece_of_data.py
> +def parse_email(email_address: str) -> Union[str, None]:
The linter complains about redefining a function. Maybe you can give the function a different name or put it in a comment like so:

```python
# def parse_email(email_address: str) -> Union[str, None]:
#     if "@" in email_address:
#         username, domain = email_address.split("@")
#         return username
#     return None
```

2023-10-02 08:10 UTC, bzaczynski commented on python-type-hints-multiple-types/02_type_hints_for_multiple_pieces_of_data.py
> +def parse_email(email_address: str) -> Union[Tuple[str, str], None]:
Another redefined function.

2023-10-02 08:10 UTC, bzaczynski commented on python-type-hints-multiple-types/05_type_hints_for_generator.py
> +def parse_emails(emails: Iterable[str]) -> Iterable[tuple[str, str]]:
Flagging yet another redefined function.

2023-10-02 08:10 UTC, bzaczynski commented on python-type-hints-multiple-types/06_type_aliases.py
> +EmailComponents = tuple[str, str] | None
Do we need to include the old-style way of defining an alias? Maybe only the new one will suffice?

```python
EmailComponents: TypeAlias = tuple[str, str] | None
```

2023-10-02 08:10 UTC, bzaczynski commented on python-type-hints-multiple-types/README.md
> +### 07_static_type_checking
If you're unsure what to put in the README file, then I'd say let's cut the highlighted lines.

2023-10-02 08:10 UTC, bzaczynski commented on python-type-hints-multiple-types/requirements.txt
> +tomli==2.0.1
I believe, we don't need this dependency, which is a backport of the standard library module `tomllib` introduced in  Python 3.11.

2023-10-03 03:42 UTC, claudian37 commented
> @claudian37 Hey Claudia! Thanks for creating a separate PR in the materials repository. Please find a few comments and let me know if you have further questions.

I've made the suggested changes. I will be traveling until Friday, so probably won't be able to make any changes before then. Thanks for reviewing my PRs!

2023-10-03 08:56 UTC, bzaczynski approved these changes
@claudian37 Thanks for the updates!

2023-10-18 01:04 UTC, merged