Materials for Pydantic: Simplifying Data Validation in Python
realpython/materials pull request #509
Opened 2024-03-03 03:23 UTC by hfhoffman1144

Materials for Pydantic: Simplifying Data Validation in Python:

https://trello.com/c/GLsjNWdF/1131-pydantic-showcase

2024-03-11 18:44 UTC, acsany requested changes
Hi @hfhoffman1144, thanks for the materials. Just a few minor notes here 😊

2024-03-11 18:44 UTC, acsany commented on python-pydantic/README.md
> +(venv) $ python -m pip install pydantic[email]
Add quotes around the package name to prevent errors on some systems:

```suggestion
(venv) $ python -m pip install "pydantic[email]"
```

2024-03-11 18:44 UTC, acsany commented on python-pydantic/pydantic_models.py
> +
I'm not sure why black wasn't flagging this, but my feeling would be to remove this line 🤔

```suggestion
```

2024-03-11 18:44 UTC, acsany commented on python-pydantic/pydantic_models.py
> +
Same as above:

```suggestion
```

2024-03-11 18:44 UTC, acsany commented on python-pydantic/validate_functions.py
> +
Same as above:

```suggestion
```

2024-03-24 21:22 UTC, brendaweles approved these changes

2024-03-24 21:25 UTC, brendaweles approved these changes

2024-03-24 21:33 UTC, brendaweles approved these changes

2024-03-24 21:36 UTC, brendaweles approved these changes

2024-03-24 21:43 UTC, brendaweles approved these changes

2024-03-24 21:44 UTC, brendaweles approved these changes

2024-03-24 22:00 UTC, brendaweles approved these changes

2024-03-24 22:07 UTC, merged