Sample code for the article on basic types
realpython/materials pull request #522
Opened 2024-04-11 15:17 UTC by lpozo

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2024-04-12 12:55 UTC, martin-martin requested changes
Two small things, thanks!

2024-04-12 12:55 UTC, martin-martin commented on python-basic-data-types/point.py
> +bool(point)
I'd suggest to make this executable with some output, either like this:

```suggestion
origin = Point(0, 0)
print(bool(origin))
point = Point(2, 4)
print(bool(point))
```

Or, potentially wrap it into the name-main idiom, but maybe no need for that for this.

2024-04-12 12:55 UTC, martin-martin commented on python-basic-data-types/escape_seqs.py
> +print("\N{rightwards arrow}")
If you agree to add the octal and hex examples to the tutorial, please add them here as well.

2024-04-15 09:29 UTC, martin-martin approved these changes
LGTM! 🎉

2024-04-28 19:53 UTC, brendaweles approved these changes

2024-04-28 19:54 UTC, merged