Python mappings
realpython/materials pull request #532
Opened 2024-05-16 22:29 UTC by stephengruppetta

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2024-05-16 22:35 UTC, stephengruppetta commented
@bzaczynski tagging in Materials

2024-05-21 07:49 UTC, bzaczynski requested changes
@stephengruppetta Just two small remarks.

2024-05-21 07:49 UTC, bzaczynski commented on python-mappings/pizza_menu.py
> +            f"'{key}' is an invalid name. All pizzas must have unique first letters"
There's a slight discrepancy between the error message here and the tutorial. Other than that, it would be nice to format the code with black.

2024-05-21 07:49 UTC, bzaczynski commented on python-mappings/README.md
> +Code defining the `PizzaMenu` class in the tutorial Python Mappings: A Comprehensive Guide
Let's use the same format of the README file as in other tutorials for consistency.

2024-05-21 10:10 UTC, bzaczynski approved these changes
@stephengruppetta Approved!

2024-05-27 23:28 UTC, brendaweles approved these changes

2024-05-27 23:31 UTC, merged