Sample materials for the article on `README` files
realpython/materials pull request #540
Opened 2024-06-12 12:17 UTC by lpozo

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2024-06-13 11:46 UTC, acsany requested changes

2024-06-13 11:46 UTC, acsany commented on readme-python-project/README-template.md
> +For more examples, please refer to the project's [Wiki][wiki] or [documentation page](page).
```suggestion
For more examples, please refer to the project's [Wiki](wiki) or [documentation page](page).
```

2024-06-13 12:40 UTC, acsany approved these changes

2024-06-17 02:49 UTC, brendaweles approved these changes

2024-06-17 02:55 UTC, merged