Sample code for the article on Python protocols
realpython/materials pull request #549
Opened 2024-06-24 14:30 UTC by lpozo

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2024-06-27 17:47 UTC, bzaczynski commented on python-protocol/contents.py
> +    def add_vide(self, title: str, path: str) -> None:
:writing_hand: **Typo**

```suggestion
    def add_video(self, title: str, path: str) -> None:
```

2024-06-27 17:52 UTC, bzaczynski requested changes
@lpozo The code looks consistent with the tutorial. There's just a single typo to fix.

2024-06-28 13:23 UTC, bzaczynski approved these changes
@lpozo Approved!

2024-07-08 15:23 UTC, brendaweles approved these changes

2024-07-08 15:25 UTC, merged