Sample code for the article on async iterators
realpython/materials pull request #557
Opened 2024-07-15 13:59 UTC by lpozo

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2024-07-18 16:50 UTC, bzaczynski requested changes
@lpozo Hey, there's a little typo in the URL in the README file :wink:

2024-07-18 16:50 UTC, bzaczynski commented on python-async-iterators/README.md
> +This folder provides the code examples for the Real Python tutorial [Asynchronous Iterators and Iterables in Python](https://realpython.com/python-async-iterator/).
:warning: **Fact Check**

Broken link due to a typo in the address:

```suggestion
This folder provides the code examples for the Real Python tutorial [Asynchronous Iterators and Iterables in Python](https://realpython.com/python-async-iterators/).
```

2024-07-19 13:00 UTC, bzaczynski approved these changes
LGTM!

2024-07-31 19:26 UTC, brendaweles approved these changes

2024-07-31 19:28 UTC, merged