Sample code for the article on lists vs tuples
realpython/materials pull request #567
Opened 2024-08-14 15:38 UTC by lpozo

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2024-08-15 08:43 UTC, martin-martin requested changes
@lpozo I'd suggest to use underscores for the script names, so that they can potentially also be moduels. Probably no one will use them like that, but I think we're generally naming Python files with underscores in this repo.

Also, a small change to show more output in the unpacking file.

2024-08-15 08:43 UTC, martin-martin commented on python-lists-tuples/unpacking.py
> +a, b
```suggestion
a = "foo"
b = "bar"
# Using a temporary variable
temp = a
a = b
b = temp
print(a, b)

a = "foo"
b = "bar"
# Using unpacking
a, b = b, a
print(a, b)
```

2024-08-16 07:32 UTC, martin-martin approved these changes

2024-08-16 07:32 UTC, martin-martin commented
Great, looks good to me ✅

2024-08-23 22:03 UTC, brendaweles approved these changes

2024-08-23 22:04 UTC, merged