Sample code for the article on building a contact book with Textual
realpython/materials pull request #573
Opened 2024-08-30 14:34 UTC by lpozo

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2024-09-05 12:31 UTC, acsany requested changes
Thanks for providing the code, @lpozo! I have two comments. Please note that you may adjust the adjacent steps with the changes 🙂

2024-09-05 12:31 UTC, acsany commented on contact-book-python-textual/source_code_step_2/rpcontacts/tui.py
> +        ("c", "clear", "Clear All"),
Later in the tutorial you'll name the method `.action_clear_all()`. You can either decide to rename the binding here, or rename the method later:

```suggestion
        ("c", "clear_all", "Clear All"),
```

2024-09-09 11:31 UTC, lpozo commented on contact-book-python-textual/source_code_step_3/rpcontacts/database.py
> +]
This was a leftover from my testing stage. Sorry.

2024-09-11 13:44 UTC, acsany approved these changes

2024-09-18 22:33 UTC, brendaweles approved these changes

2024-09-18 22:37 UTC, merged