Add slimmed-down Selenium project code
realpython/materials pull request #596
Opened 2024-10-14 13:28 UTC by martin-martin

**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

2024-10-14 13:34 UTC, martin-martin commented
@bzaczynski this is my attempt to create a slimmed-down version of the project that primarily focuses on Selenium web interactions (now following POM), but also keep the basic functionality of the music player (and a reduced---but existing---separation of concerns).

I've tried to build the project in a way so that it can lead into the project that you wrote, with the idea in mind that learners could follow your SbSP as a next step if they're interested in the music player project. At the same time, I tried to keep it simple and reduced enough that learners who are only there for an intro to Selenium would get their money's worth.

Hope this works and looking forward to your thoughts!

Linking the other PR for reference: https://github.com/realpython/materials/pull/583

2024-10-23 14:20 UTC, bzaczynski commented on python-selenium/README.md
> +(venv) $ python -m bandcamp
:wrench: **Technical Recommendation**

That doesn't work:

```
(python-selenium) $ cd src/
(python-selenium) $ python -m bandcamp/
/home/bartek/.virtualenvs/python-selenium/bin/python: No module named bandcamp/
```

A better option would be to install the package into the venv first. That way, it won't matter where you'll run the module from:

```
(python-selenium) $ python -m pip install .
(python-selenium) $ python -m bandcamp/
```

2024-10-23 15:04 UTC, bzaczynski requested changes
@martin-martin I left a few comments for you. Let me know what you think.

2025-03-16 08:39 UTC, bzaczynski reviewed
@martin-martin Hi Martin!

The code looks great overall. I only left a few minor comments for your consideration, but no explicit requests for change.

Take care!

2025-03-16 08:39 UTC, bzaczynski commented on python-selenium/README.md
> +You'll need a [Firefox Selenium driver](https://selenium-python.readthedocs.io/installation.html#drivers) called `geckodriver` to run the project as-is. Make sure to [download and install](https://gi
@martin-martin For some reason, I was having trouble starting the script due to problems with my Firefox browser. Your script would just hang without showing any output, leaving me a bit puzzled. However, I had a hunch where to look for the problem, so switching to Chrome fixed it for me. I'm wondering if we could give the users some heads up in the README about potential issues and how to troubleshoot them.

2025-03-16 08:39 UTC, bzaczynski commented on python-selenium/src/bandcamp/app/tui.py
> +    print(player._current_track._get_track_info())
@martin-martin It would be nice to include some rudimentary error handling. For example, when I request to play a track outside the valid range, the script crashes abruptly.

2025-03-16 08:39 UTC, bzaczynski commented on python-selenium/src/bandcamp/web/element.py
> +class DiscoverTrackList(WebComponent, DiscoverPageLocator, TrackLocator):
@martin-martin I believe I mentioned this before, but I'm not a big fan of abusing inheritance for code reuse like here, where you inherit the constans. Class mixins are primarily about combining _behaviors_. When you only have data attributes, it's clearer to use composition and delegation instead.

For example, instead of this:

```python
view_more_button = self._driver.find_element(*self.PAGINATION_BUTTON)
```

...you'd have that:

```python
class DiscoverTrackList(WebComponent):
    # ...
    view_more_button = self._driver.find_element(*DiscoverPageLocator.PAGINATION_BUTTON)
```

While more verbose, this version tells me exactly which web component the locator belongs to, so I don't have to hunt for it in the source code.

2025-03-16 08:39 UTC, bzaczynski commented on python-selenium/src/bandcamp/web/element.py
> +        )
@martin-martin This lambda expression is relatively dense, which is why I'd personally opt for a regular function with a descriptive name so that the code reads more easily:

```python
def _get_available_tracks(self) -> list:
    self._wait.until(track_text_loaded,
        message="Timeout waiting for track text to load",
    )

    # ...

def track_text_loaded(driver):
    return any(
        e.is_displayed() and e.text.strip()
        for e in driver.find_elements(*self.ITEM)
    )
```

2025-04-22 19:50 UTC, brendaweles approved these changes

2025-04-22 19:52 UTC, merged