Add Django User Management files
realpython/materials pull request #618
Opened 2024-11-29 16:37 UTC by acsany

Since this is a tutorial update, there are no `step/` folders

2024-12-02 12:14 UTC, bzaczynski requested changes
@acsany Overall, this looks good. I only left two small comments as of now, but let's wait until we sort out the tutorial first.

2024-12-02 12:14 UTC, bzaczynski commented on django-user-management/README.md
> +```
There's a missing step:

```
$ cd user_auth_intro/
```

2024-12-02 12:14 UTC, bzaczynski commented on django-user-management/requirements.txt
> +Django==5.1.3
We should probably include all requirements for reproducibility:

```
asgiref==3.8.1
Django==5.1.3
sqlparse==0.5.2
```

2024-12-03 09:23 UTC, bzaczynski approved these changes
@acsany LGTM!

2024-12-06 21:43 UTC, brendaweles approved these changes

2024-12-06 21:44 UTC, merged